# Generated by Django 4.1.3 on 2022-11-29 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='part.basemodel')),
                ('nom', models.CharField(max_length=155)),
                ('description', models.TextField()),
            ],
            bases=('part.basemodel',),
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='part.basemodel')),
                ('nom', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='stack/images')),
            ],
            bases=('part.basemodel',),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='part.basemodel')),
                ('nom', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('presentation', models.FileField(upload_to='projets/documents')),
                ('contenu', tinymce.models.HTMLField()),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_cat', to='part.categorie')),
                ('stack', models.ManyToManyField(related_name='stack_projects', to='part.stack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('part.basemodel',),
        ),
        migrations.CreateModel(
            name='Critique',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='part.basemodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to='part.projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_critiques', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('part.basemodel',),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='part.basemodel')),
                ('critiq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='part.critique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('part.basemodel',),
        ),
    ]
